CREATE TABLE users(
                                 id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                 name VARCHAR(30),
                                 password VARCHAR(30),
                                 role VARCHAR(8),
                                 status VARCHAR(12),
                                 email VARCHAR(30)
);
CREATE TABLE cars(
                                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                model VARCHAR(30),
                                mark VARCHAR(30),
                                car_class VARCHAR(12),
                                cost INT
);
CREATE TABLE orders(
                                  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                  userId BIGINT,
                                  driver VARCHAR(30),
                                  bill INT,
                                  status VARCHAR(15),
                                  start_date DATE,
                                  end_date DATE,
                                  FOREIGN KEY(userId) REFERENCES users(id) ON DELETE SET NULL
);
CREATE TABLE order_items(
                                       order_id BIGINT,
                                       car_id BIGINT,
                                       PRIMARY KEY(order_id, car_id),
                                       FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,
                                       FOREIGN KEY(car_id) REFERENCES cars(id) ON DELETE CASCADE
);
CREATE TABLE feedback(
                                    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                    text_field VARCHAR(128),
                                    rating INT,
                                    user_name VARCHAR(32)
);

-- Adding new users --
INSERT INTO users(name, password, role, status, email) VALUES('Garry', 'Sed111' , 'admin' , 'confirmed', 'garry@mail.com' );
INSERT INTO users(name, password, role, status, email)  VALUES('Johny', 'Ba7777' , 'manager' , 'confirmed', 'johny@mail.com' );
INSERT INTO users(name, password, role, status, email)  VALUES('Daniel', '789oP' , 'user' ,
                                                               'confirmed', 'dan@mail.com' );
INSERT INTO users(name, password, role, status, email)  VALUES('Steve', 'Cvr123' , 'user' , 'unconfirmed', 'steve@mail.com' );

--Inserting new cars --
INSERT INTO cars(model, mark, car_class, cost) VALUES( 'mustang', 'ford', 'sedan', '250');
INSERT INTO cars(model, mark, car_class, cost) VALUES( 'golf', 'volkswagen', 'hatchback', '150');
INSERT INTO cars(model, mark, car_class, cost) VALUES( 'X6', 'bmw', 'crossover', '300');
INSERT INTO cars(model, mark, car_class, cost) VALUES( 'camry', 'toyota', 'sedan', '250');
INSERT INTO cars(model, mark, car_class, cost) VALUES( 'cayen', 'porsche', 'crossover', '350');

-- Adding new order --
INSERT INTO orders(userId, driver, bill, status, start_date, end_date) VALUES (3,'no',
                                                                                          1350 ,'requested', '2018-12-04', '2018-12-07') ;

--Adding order items --
INSERT INTO order_items VALUES( 1,2);
INSERT INTO order_items VALUES( 1,3);


-- Adding new order --
INSERT INTO orders(userId, driver, bill, status, start_date, end_date) VALUES(3,'yes', 2000 ,'requested', '2019-01-07', '2018-01-09');

--Adding order items --
INSERT INTO order_items VALUES( 2,1);
INSERT INTO order_items VALUES( 2,4);
INSERT INTO order_items VALUES( 2,5);